### ISSUE TITLE
kube-prometheus-stack and Grafana dashboards

### ISSUE THREAD

**Issue by khannurien** [knative-extensions/monitoring#14]
Hi,

I think I followed the docs correctly, however Knative dashboads do not show up in Grafana after applying `https://raw.githubusercontent.com/knative-sandbox/monitoring/main/grafana/dashboards.yaml` (cf. https://github.com/knative-sandbox/monitoring/tree/main/grafana).

Note that I can import the JSON files by hand and get working dashboards. I'd like to be able to automate that part.

Here is my procedure:

```bash
# Install the Prometheus Operator through Helm
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus prometheus-community/kube-prometheus-stack -n default -f values.yaml

# Apply the ServiceMonitors/PodMonitors to collect metrics from Knative
kubectl apply -f https://raw.githubusercontent.com/knative-sandbox/monitoring/main/servicemonitor.yaml

# Import Knative Grafana dashboards
kubectl apply -f https://raw.githubusercontent.com/knative-sandbox/monitoring/main/grafana/dashboards.yaml
```

Here are the contents of my `values.yaml` file:

```yaml
kube-state-metrics:
  metricLabelsAllowlist:
   - pods=[*]
   - deployments=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance]
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
grafana:
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
```

Any help would be appreciated.

Thanks!
